version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/eng/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dev dependencies update"
  - package-ecosystem: "nuget"
    directory: "/eng/dependabot"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    labels:
      - "main dependencies update"